server.port=8080

rapidapi.key=<your-rapidapi-key>
rapidapi.airport-host=skyscanner-flights-travel-api.p.rapidapi.com
rapidapi.airport-base-url=https://skyscanner-flights-travel-api.p.rapidapi.com
rapidapi.flight-host=skyscanner-flights-travel-api.p.rapidapi.com
rapidapi.flight-base-url=https://skyscanner-flights-travel-api.p.rapidapi.com

rapidapi.hotel-host=tripadvisor16.p.rapidapi.com
rapidapi.hotel-base-url=https://tripadvisor16.p.rapidapi.com
